version: '3.8'
services:
    nest-mysql:
        image: mysql:8
        container_name: nest-mysql
        restart: always
        ports:
            - '3306:3306'
        env_file:
            - .env.development
        volumes:
            - nest-mysql:/var/lib/mysql
    redis:
        image: redis:latest
        container_name: cache
        restart: always
        ports:
            - '6379:6379'

volumes:
    nest-mysql:
        name: nest-mysql-db
    redis:
        name: nest-redis
